nelmio_api_doc:
    use_validation_groups: true
    documentation:
        servers:
          - url: https://c-costin-server.eddi.cloud
            description: MAIN SERVER
          - url: https://charlotte-carpentier-server.eddi.cloud
            description: SPARE SERVER
        info:
            title: GaraLib
            description: API Documentation for backend application GaraLib
            version: 0.1.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

        paths:
            /api/login_check:
                post:
                    tags:
                        - Authentification
                    summary: Retrieve an Token JWT
                    description: Retrieve an Token JWT with User credentials
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        email:
                                            type: string
                                            example: john.doe@mail.com
                                        password:
                                            type: string
                                            example: password
                                    type: object
                    responses:
                        '200':
                            description: Success
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: OjE2ODUwNTkyOTMsImV4cCI6MTY4NTA5NTI5Mywicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImF
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON
                    security: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc.json|/token/refresh)$)
        #host_patterns:
        #    - ^/api